name: CI/CD Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install software
        run: sudo apt update && sudo apt install python3

      - name: Clone project
        run: git clone https://github.com/Farlenski/106002

      - name: Download dependencies
        run: pip install -r requirements.txt

      - name: Create database
        run: python db.py
      
      - name: Create project build
        run: gunicorn --bind 0.0.0.0:5000 app:app

      - name: Run unit tests
        run: python -m unittest
