name: CI/CD Workflow
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install software
        run: sudo apt update && sudo apt install python3

      - name: Clone project
        run: git clone https://github.com/Farlenski/106002

      - name: Download dependencies
        run: pip3 install -r requirements.txt

      - name: Create project build
        run: gunicorn --bind 0.0.0.0:5000 app:app --daemon

      - name: Run unit tests
        run: python3 -m unittest
